//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseControls.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("宋体, 9pt")]
        public global::System.Drawing.Font Font_GlassButton {
            get {
                return ((global::System.Drawing.Font)(this["Font_GlassButton"]));
            }
            set {
                this["Font_GlassButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("宋体, 9pt")]
        public global::System.Drawing.Font Font_VistaButton {
            get {
                return ((global::System.Drawing.Font)(this["Font_VistaButton"]));
            }
            set {
                this["Font_VistaButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("宋体, 9pt")]
        public global::System.Drawing.Font Font_SkinButton {
            get {
                return ((global::System.Drawing.Font)(this["Font_SkinButton"]));
            }
            set {
                this["Font_SkinButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("宋体, 9pt")]
        public global::System.Drawing.Font Font_SplitButton {
            get {
                return ((global::System.Drawing.Font)(this["Font_SplitButton"]));
            }
            set {
                this["Font_SplitButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial Black, 15.75pt")]
        public global::System.Drawing.Font Font_CrystalButton {
            get {
                return ((global::System.Drawing.Font)(this["Font_CrystalButton"]));
            }
            set {
                this["Font_CrystalButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("宋体, 12pt")]
        public global::System.Drawing.Font Font_MyDataGridView {
            get {
                return ((global::System.Drawing.Font)(this["Font_MyDataGridView"]));
            }
            set {
                this["Font_MyDataGridView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("宋体, 9pt")]
        public global::System.Drawing.Font Font_RichTextBoxEx {
            get {
                return ((global::System.Drawing.Font)(this["Font_RichTextBoxEx"]));
            }
            set {
                this["Font_RichTextBoxEx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("宋体, 9pt")]
        public global::System.Drawing.Font Font_userTextBox {
            get {
                return ((global::System.Drawing.Font)(this["Font_userTextBox"]));
            }
            set {
                this["Font_userTextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("宋体, 9pt")]
        public global::System.Drawing.Font Font_XTextBox {
            get {
                return ((global::System.Drawing.Font)(this["Font_XTextBox"]));
            }
            set {
                this["Font_XTextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("宋体, 9pt")]
        public global::System.Drawing.Font Font_MyLabel {
            get {
                return ((global::System.Drawing.Font)(this["Font_MyLabel"]));
            }
            set {
                this["Font_MyLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("宋体, 9pt")]
        public global::System.Drawing.Font Font_MyTreeView {
            get {
                return ((global::System.Drawing.Font)(this["Font_MyTreeView"]));
            }
            set {
                this["Font_MyTreeView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ForeColor_RichTextBoxEx {
            get {
                return ((global::System.Drawing.Color)(this["ForeColor_RichTextBoxEx"]));
            }
            set {
                this["ForeColor_RichTextBoxEx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ForeColor_userTextBox {
            get {
                return ((global::System.Drawing.Color)(this["ForeColor_userTextBox"]));
            }
            set {
                this["ForeColor_userTextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ForeColor_XTextBox {
            get {
                return ((global::System.Drawing.Color)(this["ForeColor_XTextBox"]));
            }
            set {
                this["ForeColor_XTextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ForeColor_MyLabel {
            get {
                return ((global::System.Drawing.Color)(this["ForeColor_MyLabel"]));
            }
            set {
                this["ForeColor_MyLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ForeColor_MyTreeView {
            get {
                return ((global::System.Drawing.Color)(this["ForeColor_MyTreeView"]));
            }
            set {
                this["ForeColor_MyTreeView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ForeColor_VistaButton {
            get {
                return ((global::System.Drawing.Color)(this["ForeColor_VistaButton"]));
            }
            set {
                this["ForeColor_VistaButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ForeColor_MyDataGridView {
            get {
                return ((global::System.Drawing.Color)(this["ForeColor_MyDataGridView"]));
            }
            set {
                this["ForeColor_MyDataGridView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color ImageCtl_Color {
            get {
                return ((global::System.Drawing.Color)(this["ImageCtl_Color"]));
            }
            set {
                this["ImageCtl_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ImageCtl_PenWidth {
            get {
                return ((int)(this["ImageCtl_PenWidth"]));
            }
            set {
                this["ImageCtl_PenWidth"] = value;
            }
        }
    }
}
