//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseControls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaseControls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap About {
            get {
                object obj = ResourceManager.GetObject("About", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Accept {
            get {
                object obj = ResourceManager.GetObject("Accept", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add TabStrip page.
        /// </summary>
        internal static string AddTab {
            get {
                return ResourceManager.GetString("AddTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow {
            get {
                object obj = ResourceManager.GetObject("arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrow1 {
            get {
                object obj = ResourceManager.GetObject("Arrow1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowTool {
            get {
                object obj = ResourceManager.GetObject("ArrowTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BTN_FullScreen {
            get {
                object obj = ResourceManager.GetObject("BTN_FullScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BTN_Mute_Off {
            get {
                object obj = ResourceManager.GetObject("BTN_Mute_Off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BTN_Mute_On {
            get {
                object obj = ResourceManager.GetObject("BTN_Mute_On", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BTN_Pause {
            get {
                object obj = ResourceManager.GetObject("BTN_Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BTN_Play {
            get {
                object obj = ResourceManager.GetObject("BTN_Play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BTN_Stop {
            get {
                object obj = ResourceManager.GetObject("BTN_Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Calendar_bg {
            get {
                object obj = ResourceManager.GetObject("Calendar_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Calendar_bg_blue {
            get {
                object obj = ResourceManager.GetObject("Calendar_bg_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Calendar_bg_brown {
            get {
                object obj = ResourceManager.GetObject("Calendar_bg_brown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Calendar_bg_gray {
            get {
                object obj = ResourceManager.GetObject("Calendar_bg_gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Calendar_bg_green {
            get {
                object obj = ResourceManager.GetObject("Calendar_bg_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Calendar_bg_purple {
            get {
                object obj = ResourceManager.GetObject("Calendar_bg_purple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Calendar_bg_red {
            get {
                object obj = ResourceManager.GetObject("Calendar_bg_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docking.
        /// </summary>
        internal static string Category_Docking {
            get {
                return ResourceManager.GetString("Category_Docking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docking Notification.
        /// </summary>
        internal static string Category_DockingNotification {
            get {
                return ResourceManager.GetString("Category_DockingNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Changed.
        /// </summary>
        internal static string Category_PropertyChanged {
            get {
                return ResourceManager.GetString("Category_PropertyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChevronDown {
            get {
                object obj = ResourceManager.GetObject("ChevronDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChevronLeft {
            get {
                object obj = ResourceManager.GetObject("ChevronLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChevronRight {
            get {
                object obj = ResourceManager.GetObject("ChevronRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChevronUp {
            get {
                object obj = ResourceManager.GetObject("ChevronUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap closePanel {
            get {
                object obj = ResourceManager.GetObject("closePanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Collapse {
            get {
                object obj = ResourceManager.GetObject("Collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Collapse_h {
            get {
                object obj = ResourceManager.GetObject("Collapse_h", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Float).
        /// </summary>
        internal static string DockAreaEditor_FloatCheckBoxText {
            get {
                return ResourceManager.GetString("DockAreaEditor_FloatCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines if end user drag and drop docking is allowed..
        /// </summary>
        internal static string DockContent_AllowEndUserDocking_Description {
            get {
                return ResourceManager.GetString("DockContent_AllowEndUserDocking_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size to display the content in auto hide mode. Value &lt; 1 to specify the size in portion; value &gt;= 1 to specify the size in pixel..
        /// </summary>
        internal static string DockContent_AutoHidePortion_Description {
            get {
                return ResourceManager.GetString("DockContent_AutoHidePortion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/Disable the close button of the content..
        /// </summary>
        internal static string DockContent_CloseButton_Description {
            get {
                return ResourceManager.GetString("DockContent_CloseButton_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows or hides the close button of the content. This property does not function with System MDI Document Style..
        /// </summary>
        internal static string DockContent_CloseButtonVisible_Description {
            get {
                return ResourceManager.GetString("DockContent_CloseButtonVisible_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The form must be of type IDockContent..
        /// </summary>
        internal static string DockContent_Constructor_InvalidForm {
            get {
                return ResourceManager.GetString("DockContent_Constructor_InvalidForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets a value indicating in which area of the DockPanel the content allowed to show..
        /// </summary>
        internal static string DockContent_DockAreas_Description {
            get {
                return ResourceManager.GetString("DockContent_DockAreas_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the value of DockState property changed..
        /// </summary>
        internal static string DockContent_DockStateChanged_Description {
            get {
                return ResourceManager.GetString("DockContent_DockStateChanged_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the content will be hidden instead of being closed..
        /// </summary>
        internal static string DockContent_HideOnClose_Description {
            get {
                return ResourceManager.GetString("DockContent_HideOnClose_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The desired docking state when first showing..
        /// </summary>
        internal static string DockContent_ShowHint_Description {
            get {
                return ResourceManager.GetString("DockContent_ShowHint_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context menu displayed for the dock pane tab strip..
        /// </summary>
        internal static string DockContent_TabPageContextMenu_Description {
            get {
                return ResourceManager.GetString("DockContent_TabPageContextMenu_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tab text displayed in the dock pane. If not set, the Text property will be used..
        /// </summary>
        internal static string DockContent_TabText_Description {
            get {
                return ResourceManager.GetString("DockContent_TabText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text displayed when mouse hovers over the tab..
        /// </summary>
        internal static string DockContent_ToolTipText_Description {
            get {
                return ResourceManager.GetString("DockContent_ToolTipText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided value is out of range..
        /// </summary>
        internal static string DockContentHandler_AutoHidePortion_OutOfRange {
            get {
                return ResourceManager.GetString("DockContentHandler_AutoHidePortion_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Value: The value of DockAreas conflicts with current DockState..
        /// </summary>
        internal static string DockContentHandler_DockAreas_InvalidValue {
            get {
                return ResourceManager.GetString("DockContentHandler_DockAreas_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pane is invalid. Check the IsFloat and DockPanel properties of this dock pane..
        /// </summary>
        internal static string DockContentHandler_DockPane_InvalidValue {
            get {
                return ResourceManager.GetString("DockContentHandler_DockPane_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pane is invalid. Check the IsFloat and DockPanel properties of this dock pane..
        /// </summary>
        internal static string DockContentHandler_FloatPane_InvalidValue {
            get {
                return ResourceManager.GetString("DockContentHandler_FloatPane_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value, conflicts with DockableAreas  property..
        /// </summary>
        internal static string DockContentHandler_IsFloat_InvalidValue {
            get {
                return ResourceManager.GetString("DockContentHandler_IsFloat_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dock state is invalid..
        /// </summary>
        internal static string DockContentHandler_SetDockState_InvalidState {
            get {
                return ResourceManager.GetString("DockContentHandler_SetDockState_InvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dock panel is null..
        /// </summary>
        internal static string DockContentHandler_SetDockState_NullPanel {
            get {
                return ResourceManager.GetString("DockContentHandler_SetDockState_NullPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid beforeContent, it must be contained by the pane..
        /// </summary>
        internal static string DockContentHandler_Show_InvalidBeforeContent {
            get {
                return ResourceManager.GetString("DockContentHandler_Show_InvalidBeforeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DockState: Content can not be showed as &quot;Unknown&quot; or &quot;Hidden&quot;..
        /// </summary>
        internal static string DockContentHandler_Show_InvalidDockState {
            get {
                return ResourceManager.GetString("DockContentHandler_Show_InvalidDockState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The previous pane is invalid. It can not be null, and its docking state must not be auto-hide..
        /// </summary>
        internal static string DockContentHandler_Show_InvalidPrevPane {
            get {
                return ResourceManager.GetString("DockContentHandler_Show_InvalidPrevPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DockPanel can not be null..
        /// </summary>
        internal static string DockContentHandler_Show_NullDockPanel {
            get {
                return ResourceManager.GetString("DockContentHandler_Show_NullDockPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pane can not be null..
        /// </summary>
        internal static string DockContentHandler_Show_NullPane {
            get {
                return ResourceManager.GetString("DockContentHandler_Show_NullPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value, check DockableAreas property..
        /// </summary>
        internal static string DockContentHandler_ShowHint_InvalidValue {
            get {
                return ResourceManager.GetString("DockContentHandler_ShowHint_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context menu displayed for the dock pane tab strip..
        /// </summary>
        internal static string DockHandler_TabPageContextMenuStrip_Description {
            get {
                return ResourceManager.GetString("DockHandler_TabPageContextMenuStrip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PaneDiamond {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PaneDiamond", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PaneDiamond_Bottom {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PaneDiamond_Bottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PaneDiamond_Fill {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PaneDiamond_Fill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PaneDiamond_Hotspot {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PaneDiamond_Hotspot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PaneDiamond_HotspotIndex {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PaneDiamond_HotspotIndex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PaneDiamond_Left {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PaneDiamond_Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PaneDiamond_Right {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PaneDiamond_Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PaneDiamond_Top {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PaneDiamond_Top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PanelBottom {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PanelBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PanelBottom_Active {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PanelBottom_Active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PanelFill {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PanelFill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PanelFill_Active {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PanelFill_Active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PanelLeft {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PanelLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PanelLeft_Active {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PanelLeft_Active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PanelRight {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PanelRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PanelRight_Active {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PanelRight_Active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PanelTop {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PanelTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PanelTop_Active {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PanelTop_Active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press SHIFT for docking to full side..
        /// </summary>
        internal static string DockIndicator_ToolTipText {
            get {
                return ResourceManager.GetString("DockIndicator_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Content: ActiveContent must be one of the visible contents, or null if there is no visible content..
        /// </summary>
        internal static string DockPane_ActiveContent_InvalidValue {
            get {
                return ResourceManager.GetString("DockPane_ActiveContent_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockPane_AutoHide {
            get {
                object obj = ResourceManager.GetObject("DockPane_AutoHide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockPane_Close {
            get {
                object obj = ResourceManager.GetObject("DockPane_Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument: Content can not be &quot;null&quot;..
        /// </summary>
        internal static string DockPane_Constructor_NullContent {
            get {
                return ResourceManager.GetString("DockPane_Constructor_NullContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument: The content&apos;s DockPanel can not be &quot;null&quot;..
        /// </summary>
        internal static string DockPane_Constructor_NullDockPanel {
            get {
                return ResourceManager.GetString("DockPane_Constructor_NullDockPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockPane_Dock {
            get {
                object obj = ResourceManager.GetObject("DockPane_Dock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified container conflicts with the IsFloat property..
        /// </summary>
        internal static string DockPane_DockTo_InvalidContainer {
            get {
                return ResourceManager.GetString("DockPane_DockTo_InvalidContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The previous pane does not exist in the nested docking pane collection..
        /// </summary>
        internal static string DockPane_DockTo_NoPrevPane {
            get {
                return ResourceManager.GetString("DockPane_DockTo_NoPrevPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The container can not be null..
        /// </summary>
        internal static string DockPane_DockTo_NullContainer {
            get {
                return ResourceManager.GetString("DockPane_DockTo_NullContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The previous pane can not be null when the nested docking pane collection is not empty..
        /// </summary>
        internal static string DockPane_DockTo_NullPrevPane {
            get {
                return ResourceManager.GetString("DockPane_DockTo_NullPrevPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The previous pane can not be itself..
        /// </summary>
        internal static string DockPane_DockTo_SelfPrevPane {
            get {
                return ResourceManager.GetString("DockPane_DockTo_SelfPrevPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FloatWindow property can not be set to &quot;null&quot; when DockState is DockState.Float..
        /// </summary>
        internal static string DockPane_FloatWindow_InvalidValue {
            get {
                return ResourceManager.GetString("DockPane_FloatWindow_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockPane_Option {
            get {
                object obj = ResourceManager.GetObject("DockPane_Option", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockPane_OptionOverflow {
            get {
                object obj = ResourceManager.GetObject("DockPane_OptionOverflow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Content: Content not within the collection..
        /// </summary>
        internal static string DockPane_SetContentIndex_InvalidContent {
            get {
                return ResourceManager.GetString("DockPane_SetContentIndex_InvalidContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Index: The index is out of range..
        /// </summary>
        internal static string DockPane_SetContentIndex_InvalidIndex {
            get {
                return ResourceManager.GetString("DockPane_SetContentIndex_InvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state for the dock pane is invalid..
        /// </summary>
        internal static string DockPane_SetDockState_InvalidState {
            get {
                return ResourceManager.GetString("DockPane_SetDockState_InvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockPaneCaption_AutoHideNo {
            get {
                object obj = ResourceManager.GetObject("DockPaneCaption_AutoHideNo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockPaneCaption_AutoHideYes {
            get {
                object obj = ResourceManager.GetObject("DockPaneCaption_AutoHideYes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockPaneCaption_CloseDisabled {
            get {
                object obj = ResourceManager.GetObject("DockPaneCaption_CloseDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockPaneCaption_CloseEnabled {
            get {
                object obj = ResourceManager.GetObject("DockPaneCaption_CloseEnabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockPaneCaption_OptionsDisabled {
            get {
                object obj = ResourceManager.GetObject("DockPaneCaption_OptionsDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockPaneCaption_OptionsEnabled {
            get {
                object obj = ResourceManager.GetObject("DockPaneCaption_OptionsEnabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Hide.
        /// </summary>
        internal static string DockPaneCaption_ToolTipAutoHide {
            get {
                return ResourceManager.GetString("DockPaneCaption_ToolTipAutoHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string DockPaneCaption_ToolTipClose {
            get {
                return ResourceManager.GetString("DockPaneCaption_ToolTipClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string DockPaneCaption_ToolTipOptions {
            get {
                return ResourceManager.GetString("DockPaneCaption_ToolTipOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Content: The content must be auto-hide state and associates with this DockPanel..
        /// </summary>
        internal static string DockPanel_ActiveAutoHideContent_InvalidValue {
            get {
                return ResourceManager.GetString("DockPanel_ActiveAutoHideContent_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the value of ActiveContentProperty changed..
        /// </summary>
        internal static string DockPanel_ActiveContentChanged_Description {
            get {
                return ResourceManager.GetString("DockPanel_ActiveContentChanged_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the value of ActiveDocument property changed..
        /// </summary>
        internal static string DockPanel_ActiveDocumentChanged_Description {
            get {
                return ResourceManager.GetString("DockPanel_ActiveDocumentChanged_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the value of ActivePane property changed..
        /// </summary>
        internal static string DockPanel_ActivePaneChanged_Description {
            get {
                return ResourceManager.GetString("DockPanel_ActivePaneChanged_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines if the drag and drop docking is allowed..
        /// </summary>
        internal static string DockPanel_AllowEndUserDocking_Description {
            get {
                return ResourceManager.GetString("DockPanel_AllowEndUserDocking_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines if the drag and drop nested docking is allowed..
        /// </summary>
        internal static string DockPanel_AllowEndUserNestedDocking_Description {
            get {
                return ResourceManager.GetString("DockPanel_AllowEndUserNestedDocking_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when a content added to the DockPanel..
        /// </summary>
        internal static string DockPanel_ContentAdded_Description {
            get {
                return ResourceManager.GetString("DockPanel_ContentAdded_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when a content removed from the DockPanel..
        /// </summary>
        internal static string DockPanel_ContentRemoved_Description {
            get {
                return ResourceManager.GetString("DockPanel_ContentRemoved_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default size of float window..
        /// </summary>
        internal static string DockPanel_DefaultFloatWindowSize_Description {
            get {
                return ResourceManager.GetString("DockPanel_DefaultFloatWindowSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides Visual Studio .Net style docking..
        /// </summary>
        internal static string DockPanel_Description {
            get {
                return ResourceManager.GetString("DockPanel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of the bottom docking window. Value &lt; 1 to specify the size in portion; value &gt; 1 to specify the size in pixels..
        /// </summary>
        internal static string DockPanel_DockBottomPortion_Description {
            get {
                return ResourceManager.GetString("DockPanel_DockBottomPortion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of the left docking window. Value &lt; 1 to specify the size in portion; value &gt; 1 to specify the size in pixels..
        /// </summary>
        internal static string DockPanel_DockLeftPortion_Description {
            get {
                return ResourceManager.GetString("DockPanel_DockLeftPortion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The visual skin to use when displaying the docked windows..
        /// </summary>
        internal static string DockPanel_DockPanelSkin {
            get {
                return ResourceManager.GetString("DockPanel_DockPanelSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of the right docking window. Value &lt; 1 to specify the size in portion; value &gt; 1 to specify the size in pixels..
        /// </summary>
        internal static string DockPanel_DockRightPortion_Description {
            get {
                return ResourceManager.GetString("DockPanel_DockRightPortion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of the top docking window. Value &lt; 1 to specify the size in portion; value &gt; 1 to specify the size in pixels..
        /// </summary>
        internal static string DockPanel_DockTopPortion_Description {
            get {
                return ResourceManager.GetString("DockPanel_DockTopPortion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The style of the document window..
        /// </summary>
        internal static string DockPanel_DocumentStyle_Description {
            get {
                return ResourceManager.GetString("DockPanel_DocumentStyle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines where the tab strip for Document style content is drawn..
        /// </summary>
        internal static string DockPanel_DocumentTabStripLocation {
            get {
                return ResourceManager.GetString("DockPanel_DocumentTabStripLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DockPanel has already been initialized..
        /// </summary>
        internal static string DockPanel_LoadFromXml_AlreadyInitialized {
            get {
                return ResourceManager.GetString("DockPanel_LoadFromXml_AlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file&apos;s version is invalid..
        /// </summary>
        internal static string DockPanel_LoadFromXml_InvalidFormatVersion {
            get {
                return ResourceManager.GetString("DockPanel_LoadFromXml_InvalidFormatVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML file format is invalid..
        /// </summary>
        internal static string DockPanel_LoadFromXml_InvalidXmlFormat {
            get {
                return ResourceManager.GetString("DockPanel_LoadFromXml_InvalidXmlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parent form. When using DockingMdi or SystemMdi document style, the DockPanel control must be the child control of the main MDI container form..
        /// </summary>
        internal static string DockPanel_ParentForm_Invalid {
            get {
                return ResourceManager.GetString("DockPanel_ParentForm_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DockPanel configuration file. Author: Weifen Luo, all rights reserved..
        /// </summary>
        internal static string DockPanel_Persistor_XmlFileComment1 {
            get {
                return ResourceManager.GetString("DockPanel_Persistor_XmlFileComment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!! AUTOMATICALLY GENERATED FILE. DO NOT MODIFY !!!.
        /// </summary>
        internal static string DockPanel_Persistor_XmlFileComment2 {
            get {
                return ResourceManager.GetString("DockPanel_Persistor_XmlFileComment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether the control layout is right-to-left when the RightToLeft property is set to Yes..
        /// </summary>
        internal static string DockPanel_RightToLeftLayout_Description {
            get {
                return ResourceManager.GetString("DockPanel_RightToLeftLayout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Index: The index is out of range..
        /// </summary>
        internal static string DockPanel_SetPaneIndex_InvalidIndex {
            get {
                return ResourceManager.GetString("DockPanel_SetPaneIndex_InvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pane: DockPane not within the collection..
        /// </summary>
        internal static string DockPanel_SetPaneIndex_InvalidPane {
            get {
                return ResourceManager.GetString("DockPanel_SetPaneIndex_InvalidPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines if the document icon will be displayed in the tab strip..
        /// </summary>
        internal static string DockPanel_ShowDocumentIcon_Description {
            get {
                return ResourceManager.GetString("DockPanel_ShowDocumentIcon_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockPaneStrip_CloseDisabled {
            get {
                object obj = ResourceManager.GetObject("DockPaneStrip_CloseDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockPaneStrip_CloseEnabled {
            get {
                object obj = ResourceManager.GetObject("DockPaneStrip_CloseEnabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockPaneStrip_OptionsDisabled {
            get {
                object obj = ResourceManager.GetObject("DockPaneStrip_OptionsDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockPaneStrip_OptionsEnabled {
            get {
                object obj = ResourceManager.GetObject("DockPaneStrip_OptionsEnabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockPaneStrip_OverflowDisabled {
            get {
                object obj = ResourceManager.GetObject("DockPaneStrip_OverflowDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockPaneStrip_OverflowEnabled {
            get {
                object obj = ResourceManager.GetObject("DockPaneStrip_OverflowEnabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string DockPaneStrip_ToolTipClose {
            get {
                return ResourceManager.GetString("DockPaneStrip_ToolTipClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Files.
        /// </summary>
        internal static string DockPaneStrip_ToolTipOptions {
            get {
                return ResourceManager.GetString("DockPaneStrip_ToolTipOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window List.
        /// </summary>
        internal static string DockPaneStrip_ToolTipWindowList {
            get {
                return ResourceManager.GetString("DockPaneStrip_ToolTipWindowList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ellipse {
            get {
                object obj = ResourceManager.GetObject("Ellipse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Exit {
            get {
                object obj = ResourceManager.GetObject("Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Expand {
            get {
                object obj = ResourceManager.GetObject("Expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Expand_h {
            get {
                object obj = ResourceManager.GetObject("Expand_h", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument: DockPanel can not be &quot;null&quot;..
        /// </summary>
        internal static string FloatWindow_Constructor_NullDockPanel {
            get {
                return ResourceManager.GetString("FloatWindow_Constructor_NullDockPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Index: The index is out of range..
        /// </summary>
        internal static string FloatWindow_SetPaneIndex_InvalidIndex {
            get {
                return ResourceManager.GetString("FloatWindow_SetPaneIndex_InvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pane: DockPane not within the collection..
        /// </summary>
        internal static string FloatWindow_SetPaneIndex_InvalidPane {
            get {
                return ResourceManager.GetString("FloatWindow_SetPaneIndex_InvalidPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] harrow {
            get {
                object obj = ResourceManager.GetObject("harrow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] hmove {
            get {
                object obj = ResourceManager.GetObject("hmove", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DockPanel..
        /// </summary>
        internal static string IDockDragSource_DockTo_InvalidPanel {
            get {
                return ResourceManager.GetString("IDockDragSource_DockTo_InvalidPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} can&apos;t be null.
        /// </summary>
        internal static string IDS_ArgumentException {
            get {
                return ResourceManager.GetString("IDS_ArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of &apos;{0}&apos; is not valid for &apos;{1}&apos;. &apos;{1}&apos; must be greater than or equal to {2}.
        ///Parameter name: {1}.
        /// </summary>
        internal static string IDS_InvalidOperationExceptionInteger {
            get {
                return ResourceManager.GetString("IDS_InvalidOperationExceptionInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Line {
            get {
                object obj = ResourceManager.GetObject("Line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap menu_back {
            get {
                object obj = ResourceManager.GetObject("menu_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap movie {
            get {
                object obj = ResourceManager.GetObject("movie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap movie_track_back {
            get {
                object obj = ResourceManager.GetObject("movie_track_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PANEL_Center {
            get {
                object obj = ResourceManager.GetObject("PANEL_Center", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PANEL_Fill {
            get {
                object obj = ResourceManager.GetObject("PANEL_Fill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PANEL_Left {
            get {
                object obj = ResourceManager.GetObject("PANEL_Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PANEL_Right {
            get {
                object obj = ResourceManager.GetObject("PANEL_Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rectangular {
            get {
                object obj = ResourceManager.GetObject("Rectangular", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Redo {
            get {
                object obj = ResourceManager.GetObject("Redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sound_track_back {
            get {
                object obj = ResourceManager.GetObject("sound_track_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Text {
            get {
                object obj = ResourceManager.GetObject("Text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TRACK_Thumb {
            get {
                object obj = ResourceManager.GetObject("TRACK_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TRACK_Thumb1 {
            get {
                object obj = ResourceManager.GetObject("TRACK_Thumb1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
